FROM alpine:3.15
LABEL maintainer="Charlie Lewis <clewis@iqt.org>"
RUN apk add --update curl mosquitto && rm -rf /var/cache/apk/*
COPY mosquitto.conf /etc/mosquitto/mosquitto.conf
EXPOSE 1883
ENTRYPOINT ["/usr/sbin/mosquitto", "-v", "-c", "/etc/mosquitto/mosquitto.conf"]
