FROM iqtlabs/gamutrf-gnuradio-deps:latest
WORKDIR /root
RUN git clone https://github.com/anarkiwi/gnuradio -b st2
WORKDIR /root/gnuradio/build
RUN CMAKE_CXX_STANDARD=17 cmake -DENABLE_DEFAULT=OFF -DENABLE_PYTHON=ON -DENABLE_GNURADIO_RUNTIME=ON -DENABLE_GR_BLOCKS=ON -DENABLE_GR_FFT=ON -DENABLE_GR_FILTER=ON -DENABLE_GR_ANALOG=ON -DENABLE_GR_UHD=ON -DENABLE_GR_NETWORK=ON -DENABLE_GR_SOAPY=ON .. && make -j "$(nproc)" && make install
RUN ln -s /usr/local/lib/python3/dist-packages/* /usr/local/lib/python3.10/dist-packages
RUN ldconfig -v
RUN python3 -c "from gnuradio import analog, blocks, gr, network, soapy"
