FROM ubuntu:22.04
LABEL maintainer="Charlie Lewis <clewis@iqt.org>"
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common && \
    apt-get -y --no-install-recommends install \
    python3 python3-pip sox
COPY samples2raw-requirements.txt samples2raw-requirements.txt
RUN pip3 install -r samples2raw-requirements.txt
COPY gamutrf/samples2raw.py /root/samples2raw.py
COPY gamutrf/utils.py /root/gamutrf/utils.py
ENV PYTHONPATH /root
RUN /root/samples2raw.py --help
ENTRYPOINT ["/usr/bin/python3", "/root/samples2raw.py"]
CMD ["--help"]
