FROM ubuntu:20.04
RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common && \
    apt-get -y --no-install-recommends install \
    build-essential \
    cmake \
    g++ \
    gcc \
    git \
    libbladerf-dev \
    libboost-all-dev \
    libev-dev \
    libfftw3-dev \
    libgmp-dev \
    libgsl-dev \
    liblimesuite-dev \
    liblog4cpp5-dev \
    libpython3-dev \
    libthrift-dev \
    libuhd-dev \
    libunwind-dev \
    libusb-1.0-0-dev \
    libusb-1.0-0 \
    libvolk2-dev \
    make \
    netcat \
    pkg-config \
    python3-bladerf \
    python3-mako \
    python3-numpy \
    python3-pip \
    python3-pygccxml \
    python3-uhd \
    swig \
    uhd-host \
    wget
RUN /usr/lib/uhd/utils/uhd_images_downloader.py -t "b2|usb"
WORKDIR /root
# https://wiki.gnuradio.org/index.php/GNU_Radio_3.9_OOT_Module_Porting_Guide
RUN wget -q -O- https://github.com/pybind/pybind11/archive/v2.5.0.tar.gz |tar -zxvf -
RUN git clone https://github.com/gnuradio/volk -b v2.5.0
RUN git clone https://github.com/anarkiwi/gnuradio -b st2
RUN git clone https://github.com/pothosware/SoapySDR -b soapy-sdr-0.8.1
WORKDIR /root/pybind11-2.5.0/build
RUN cmake -DPYBIND11_TEST="" .. && make -j "$(nproc)" && make install
WORKDIR /root/volk/build
RUN git submodule update --init
RUN cmake .. && make -j "$(nproc)" && make install
WORKDIR /root/SoapySDR/build
RUN cmake .. && make -j "$(nproc)" && make install
WORKDIR /root/gnuradio/build
RUN cmake -DENABLE_DEFAULT=OFF -DENABLE_PYTHON=ON -DENABLE_GNURADIO_RUNTIME=ON -DENABLE_GR_BLOCKS=ON -DENABLE_GR_FFT=ON -DENABLE_GR_FILTER=ON -DENABLE_GR_ANALOG=ON -DENABLE_GR_UHD=ON -DENABLE_GR_SOAPY=ON .. && make -j "$(nproc)" && make install
RUN ln -s /usr/local/lib/python3/dist-packages/* /usr/local/lib/python3.8/dist-packages
RUN ldconfig -v
RUN python3 -c "from gnuradio import soapy"
