version: "3.3"
networks:
  gamutrf:
services:
  gamutrf:
    image: iqtlabs/gamutrf:latest
    depends_on:
      sigfinder:
        condition: service_started
    networks:
      - gamutrf
    cap_add:
      - SYS_NICE
      - SYS_RAWIO
    devices:
      - /dev/bus/usb:/dev/bus/usb
    command:
      - --logaddr=sigfinder
      - --igain=30
      - '--freq-start=${FREQ_START}'
      - '--freq-end=${FREQ_END}'
  sigfinder:
    restart: on-failure
    image: iqtlabs/gamutrf-sigfinder:latest
    networks:
      - gamutrf
    volumes:
      - '${VOL_PREFIX}:/logs'
    command:
      - --logaddr=sigfinder
      - --log=/logs/scan.csv
