FROM python:3-slim
WORKDIR /root
COPY requirements.txt /root/requirements.txt
RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg gcc git gnuplot g++ libev-dev python3-pip && pip3 install -r /root/requirements.txt
COPY gamutrf/sigwindows.py /root/gamutrf/sigwindows.py
COPY gamutrf/scan2mp4.py /root/scan2mp4.py
ENV PYTHONPATH /root
ENTRYPOINT ["python3", "/root/scan2mp4.py"]
CMD ["--help"]
