FROM iqtlabs/gamutrf:latest
WORKDIR /root
RUN mkdir -p /data/gamutrf
COPY requirements.txt /root/requirements.txt
RUN pip3 install -r /root/requirements.txt
RUN git clone https://github.com/Nuand/bladeRF.git -b 2021.10
RUN git clone https://github.com/anarkiwi/lime-tools -b samples
WORKDIR /root/bladeRF/host/build
RUN cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DINSTALL_UDEV_RULES=ON -DENABLE_BACKEND_LIBUSB=TRUE .. && make -j "$(nproc)" && make install && ldconfig -v
COPY . /root/gamutrf
WORKDIR /root/lime-tools/build
RUN cmake .. && make install
WORKDIR /root/gamutrf
RUN pip3 install .
EXPOSE 8000
ENV UHD_IMAGES_DIR /usr/share/uhd/images
ENTRYPOINT ["gamutrf-api"]
