FROM python:3-slim
LABEL maintainer="Charlie Lewis <clewis@iqt.org>"
ENV PYTHONUNBUFFERED 1
RUN apt-get update && apt-get install --no-install-recommends -yq gcc libev-dev python3-dev  && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY compass-requirements.txt /root/requirements.txt
RUN pip3 install -r /root/requirements.txt
COPY gamutrf/compass.py /root/compass.py
WORKDIR /root
EXPOSE 8000
ENTRYPOINT ["nice", "-n", "-19", "python3", "/root/compass.py"]
CMD [""]
