version: "3.3"
networks:
  gamutrf:
services:
  gamutrf:
    image: iqtlabs/gamutrf:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - gamutrf
    cap_add:
      - SYS_NICE
      - SYS_RAWIO
    devices:
      - /dev/bus/usb:/dev/bus/usb
    command:
      - --logaddr=sigfinder
      - --igain=30
  sigfinder:
    restart: on-failure
    image: iqtlabs/gamutrf-sigfinder:latest
    build:
      context: .
      dockerfile: Dockerfile.sigfinder
    networks:
      - gamutrf
    volumes:
      - '.:/logs'
    command:
      - --logaddr=sigfinder
      - --log=/logs/ettus_scan.csv
