FROM python:3-slim
LABEL maintainer="Charlie Lewis <clewis@iqt.org>"
ENV PYTHONUNBUFFERED 1
COPY compass-requirements.txt /root/requirements.txt
RUN pip3 install -r /root/requirements.txt
COPY gamutrf/compass.py /root/compass.py
EXPOSE 8000
ENTRYPOINT ["nice", "-n", "-19", "python3", "compass.py"]
CMD [""]
