FROM iqtlabs/gamutrf:latest
RUN apt-get update && apt-get install --no-install-recommends -yq python3-dev build-essential gcc libev-dev && apt-get clean && rm -rf /var/lib/apt/lists/*
WORKDIR /root
RUN mkdir -p /data/gamutrf
COPY requirements.txt /root/requirements.txt
RUN pip3 install -r /root/requirements.txt
COPY . /root/gamutrf
WORKDIR /root/gamutrf
RUN pip3 install .
EXPOSE 8000
ENTRYPOINT ["gamutrf-api"]
