FROM ubuntu:22.04
LABEL maintainer="Charlie Lewis <clewis@iqt.org>"
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common gnuradio python3 python3-pip soapysdr-module-bladerf
COPY rssi-requirements.txt rssi-requirements.txt
RUN pip3 install -r rssi-requirements.txt
COPY gamutrf/birds_eye_rssi.py /root/birds_eye_rssi.py
RUN /root/birds_eye_rssi.py --help
ENTRYPOINT ["/usr/bin/python3", "/root/birds_eye_rssi.py"]
CMD ["--help"]
