---
version: "3.3"
networks:
  gamutrf:
services:
  sigfinder:
    restart: always
    image: iqtlabs/gamutrf:latest
    shm_size: 128m
    privileged: true
    networks:
      - gamutrf
    ports:
      - '80:80'
      - '9002:9000'
    volumes:
      - '${VOL_PREFIX}:/logs'
    command:
      - gamutrf-sigfinder
      - --scanners=gamutrf:10000
      - --log=/logs/scan.log
      - --detection_type=narrowband
      - --record_secs=1
      - --max_recorder_signals=5
      - --db_rolling_factor=0
    environment:
      - "PEAK_TRIGGER=0"
      - "PIN_TRIGGER=17"
