version: "3.3"
networks:
  gamutrf:
services:
  torchserve:
    restart: always
    image: iqtlabs/torchserve:v0.0.4
    networks:
      - gamutrf
    ports:
      - '8080:8080'
      - '8081:8081'
    volumes:
      - '${VOL_PREFIX}/model_store:/model_store'
      - '/root/.cache:/root/.cache'
    command:
      - --models mini2_snr=mini2_snr.mar
