version: "3.3"
networks:
  gamutrf:
services:
  torchserve:
    restart: always
    image: iqtlabs/cuda-torchserve:latest
    networks:
      - gamutrf
    ports:
      - '8080:8080'
    volumes:
      - '${VOL_PREFIX}:/model_store'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command:
      - --models mini2_snr=mini2_snr.mar
