# On Pi4/Ubuntu, also requires systemd.unified_cgroup_hierarchy=0 added to /boot/firmware/cmdline.txt,
# to fall back to cgroup v1.
version: "3.3"
networks:
  gamutrf:
services:
  api:
    restart: always
    image: iqtlabs/gamutrf:latest
    networks:
      - gamutrf
    ports:
      - '8000:8000'
    cap_add:
      - SYS_NICE
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - '${VOL_PREFIX}:/data'
    environment:
      - 'WORKER_NAME=${WORKER_NAME}'
      - 'ORCHESTRATOR=${ORCHESTRATOR}'
      - 'ANTENNA=${ANTENNA}'
      - 'NFFT=256'
    command:
      - nice
      - '-n'
      - '-19'
      - gamutrf-api
      - --no-agc
      - --rxb=62914560
      - '--gain=${GAIN}'
      - --qsize=5
      #- --rssi
      #- --rssi_threshold=-110
      #- --rssi_throttle=10
      - --use_mavlink_gps
      - --use_mavlink_heading
      - --mavlink_api_server=10.20.25.43
  watchtower:
    image: containrrr/watchtower:latest
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "WATCHTOWER_POLL_INTERVAL=3600"
      - "WATCHTOWER_CLEANUP=true"
      - "WATCHTOWER_INCLUDE_RESTARTING=true"
      - "WATCHTOWER_INCLUDE_STOPPED=true"
      - "WATCHTOWER_REVIVE_STOPPED=true"
