---
# On Pi4/Ubuntu, also requires systemd.unified_cgroup_hierarchy=0 added to
# /boot/firmware/cmdline.txt, to fall back to cgroup v1.
version: "3.3"
networks:
  gamutrf:
  default:
    external: true
    name: none
services:
  worker:
    restart: always
    image: iqtlabs/gamutrf:latest
    networks:
      - gamutrf
    ports:
      - '8000:8000'
    cap_add:
      - SYS_NICE
      - SYS_RAWIO
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - '${VOL_PREFIX}:/data'
    environment:
      - 'WORKER_NAME=${WORKER_NAME}'
      - 'ORCHESTRATOR=${ORCHESTRATOR}'
      - 'ANTENNA=${ANTENNA}'
    command:
      - nice
      - '-n'
      - '-19'
      - gamutrf-worker
      - --no-agc
      - --rxb=62914560
      - '--gain=${GAIN}'
      - --qsize=5
      # - --rssi_threshold=-110
      # - --rssi_throttle=10
      # - --use_external_gps
      # - --use_external_heading
      # - --external_gps_server=$ORCHESTRATOR
