FROM ubuntu:22.04 as vkfft-builder
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  ca-certificates \
  cmake \
  git \
  libvulkan-dev \
  python3-dev
WORKDIR /root
RUN git clone https://github.com/DTolm/VkFFT -b v1.3.2
WORKDIR /root/VkFFT/build
RUN CMAKE_BUILD_TYPE=Release cmake -DGLSLANG_GIT_TAG=13.0.0 .. && make -j "$(nproc)"

FROM ubuntu:22.04
# TODO: ideally, should be packaged such that cmake can find it.
RUN if [ "$(arch)" = "x86_64" ] ; then \
        apt-get update && \
        apt-get install -y --no-install-recommends ca-certificates dirmngr gpg-agent gpg wget && \
        apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/$(arch)/3bf863cc.pub && \
        echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/$(arch)/ /" | tee /etc/apt/sources.list.d/nvidia.list && \
        apt-get update && \
        apt-get install -y --no-install-recommends libnvidia-gl-545 ; \
    fi && \
    apt-get update && apt-get install -y --no-install-recommends \
        libvulkan1
COPY --from=vkfft-builder /root/VkFFT /root/VkFFT
CMD ["/root/VkFFT/build/VkFFT_TestSuite", "-devices"]

# Test that GPU can be accessed by VkFFT:
# $ docker run --gpus all --device /dev/dri/renderD128:/dev/dri/renderD128 -ti iqtlabs/gamutrf-vkfft
# Device id: 0 name: NVIDIA GeForce RTX 4070 Ti API:1.3.260
