FROM iqtlabs/gnuradio:3.10.6 as builder
ENV DEBIAN_FRONTEND noninteractive
WORKDIR /root
RUN git clone https://github.com/pothosware/SoapyBladeRF -b soapy-bladerf-0.4.1
RUN git clone https://github.com/pothosware/SoapyUHD -b soapy-uhd-0.4.1
RUN git clone https://github.com/Nuand/bladeRF.git -b 2023.02
RUN git clone https://github.com/anarkiwi/lime-tools -b samples
RUN git clone https://github.com/iqtlabs/uhd_sample_recorder -b v1.0.4
RUN git clone https://github.com/iqtlabs/gr-iqtlabs -b 1.0.27
WORKDIR /root/uhd_sample_recorder
RUN ./install-deps.sh && ./build.sh
WORKDIR /root/uhd_sample_recorder/build
RUN cp uhd_sample_recorder /usr/local/bin
WORKDIR /root/SoapyBladeRF/build
RUN cmake .. && make -j "$(nproc)" && make install
WORKDIR /root/SoapyUHD/build
RUN cmake .. && make -j "$(nproc)" && make install
WORKDIR /root/gr-iqtlabs/build
RUN apt-get update && apt-get install -y --no-install-recommends libopencv-dev && cmake .. && make install
WORKDIR /root/bladeRF/host/build
RUN cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local -DINSTALL_UDEV_RULES=ON -DENABLE_BACKEND_LIBUSB=TRUE .. && make -j "$(nproc)" && make install
WORKDIR /root/lime-tools/build
RUN cmake .. && make install

FROM iqtlabs/gnuradio:3.10.6
ENV DEBIAN_FRONTEND noninteractive
COPY --from=builder /usr/local /usr/local
RUN apt-get update && apt-get install -y --no-install-recommends \
    libopencv-core4.5d \
    libopencv-imgcodecs4.5d \
    libopencv-imgproc4.5d && apt-get -y -q clean && rm -rf /var/lib/apt/lists/*
RUN ldconfig -v
RUN ln -sf /usr/local/lib/python3/dist-packages/* /usr/local/lib/python3.10/dist-packages
RUN python3 -c "from gnuradio import soapy, iqtlabs"
