FROM ubuntu:22.04 as builder
RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common && \
    apt-get -y --no-install-recommends install \
    build-essential \
    cmake \
    git \
    python3-mako python3-distutils portaudio19-dev libsoxr-dev libusb-1.0-0-dev libairspy-dev libsndfile1-dev librtlsdr-dev
WORKDIR /root
RUN git clone https://github.com/gnuradio/volk -b v2.5.2
RUN git clone https://github.com/airspy/airspyhf -b 1.6.8
RUN git clone https://github.com/jj1bdx/airspy-fmradion -b 20230529-0
WORKDIR /root/volk/build
RUN git submodule update --init
RUN cmake .. && make && make install
WORKDIR /root/airspyhf/build
RUN cmake .. && make && make install
WORKDIR /root/airspy-fmradion/build
RUN git submodule update --init
RUN cmake .. && make && make install
FROM ubuntu:22.04
RUN apt-get update && apt-get install -y --no-install-recommends \
    libportaudio2 libsoxr0 libusb-1.0-0 libairspy0 libsndfile1 librtlsdr0
COPY --from=builder /usr/local /usr/local
RUN ldconfig
RUN ldd /usr/local/bin/airspy-fmradion
ENTRYPOINT ["/usr/local/bin/airspy-fmradion"]
# example usage:
# recording must be already tuned/centered on frequency to decode.
# airspy-fmradion -t filesource -c srate=20000000,raw,format=S16_LE,filename=test_98200000Hz_20000000sps.s16 -W test.wav
