FROM ubuntu:22.04 as torchsig-builder
WORKDIR /root
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends build-essential ca-certificates cmake git python3-pip python3-dev && pip install -U pip
# Cause torch CPU only to be installed, no cuda dependencies
RUN pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
RUN git clone https://github.com/TorchDSP/torchsig -b v0.5.1
WORKDIR /root/torchsig
# Remove dependencies that transforms don't need.
RUN sed -i -E "s/torch==[0-9\.]+/torch/g" pyproject.toml
RUN for d in h5py scikit-learn sympy timm torchmetrics torchvision pytorch_lightning ; do sed -i -E "/${d}/d" pyproject.toml ; done
RUN pip install .

FROM iqtlabs/gamutrf:latest
WORKDIR /root
ENV DEBIAN_FRONTEND noninteractive
# TODO: find a better way cherrypick just Torchsig itself, without Torch et al. Torchsig transforms have dependencies on
# Torch, even though we don't need Torch for the standalone transforms we want.
COPY --from=torchsig-builder /usr/local/lib/python3.10/dist-packages /usr/local/lib/python3.10/dist-packages
RUN python3 -c "from torchsig.transforms import transforms"
RUN python3 -c "from gamutrf import grscan"
COPY augment/augment.py /root/augment.py
# Ensure transforms work despite the dependency mangling.
RUN dd if=/dev/zero of=/tmp/gamutrf_recording_ettus__gain40_1_1Hz_1000sps.raw bs=8 count=1000 && /root/augment.py /tmp/gamutrf_recording_ettus__gain40_1_1Hz_1000sps.raw /tmp 1 "ST.Compose([ST.Identity()])" && diff -b /tmp/gamutrf_recording_ettus__gain40_1_1Hz_1000sps.raw /tmp/augmented-0-gamutrf_recording_ettus__gain40_1_1Hz_1000sps && rm -f /tmp/gamutrf*

ENTRYPOINT ["/root/augment.py"]
