FROM ubuntu:22.04 as vkfft-builder
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  ca-certificates \
  cmake \
  git \
  libvulkan-dev \
  python3-dev
WORKDIR /root
RUN git clone https://github.com/DTolm/VkFFT -b v1.3.1
RUN git clone https://github.com/KhronosGroup/SPIRV-Tools -b v2023.2
WORKDIR /root/SPIRV-Tools/external
RUN git clone https://github.com/KhronosGroup/SPIRV-Headers -b sdk-1.3.246.1 spirv-headers
WORKDIR /root/SPIRV-Tools/build
RUN CMAKE_BUILD_TYPE=Release cmake .. && make -j "$(nproc)" && make install
WORKDIR /root/VkFFT/build
RUN CMAKE_BUILD_TYPE=Release cmake -DALLOW_EXTERNAL_SPIRV_TOOLS=ON .. && make -j "$(nproc)"

FROM ubuntu:22.04
# TODO: ideally, should be packaged such that cmake can find it.
COPY --from=vkfft-builder /root/SPIRV-Tools/build/source/opt/libSPIRV-Tools-opt.a /root/SPIRV-Tools/build/source/opt/libSPIRV-Tools-opt.a
COPY --from=vkfft-builder /root/SPIRV-Tools/build/source/libSPIRV-Tools.a /root/SPIRV-Tools/build/source/libSPIRV-Tools.a
COPY --from=vkfft-builder /root/VkFFT /root/VkFFT
