FROM ubuntu:22.04
RUN apt-get update && apt-get install -y --no-install-recommends software-properties-common && \
    apt-get -y --no-install-recommends install \
    build-essential \
    cmake \
    g++ \
    gcc \
    git \
    libarmadillo-dev \
    libbladerf-dev \
    libboost-all-dev \
    liblimesuite-dev \
    libpython3-dev \
    libuhd-dev \
    libusb-1.0-0-dev \
    libusb-1.0-0 \
    libvulkan-dev \
    make \
    netcat \
    pkg-config \
    pybind11-dev \
    python3-bladerf \
    python3-mako \
    python3-numpy \
    python3-packaging \
    python3-pip \
    python3-pygccxml \
    python3-uhd \
    python3-zmq \
    sudo \
    swig \
    uhd-host \
    unzip \
    wget
RUN /usr/lib/uhd/utils/uhd_images_downloader.py -t "b2|usb"
