# nosemgrep:github.workflows.config.dockerfile-source-not-pinned
FROM ubuntu:22.04 as installer
ARG POETRY_CACHE
ENV DEBIAN_FRONTEND noninteractive
ENV PATH="${PATH}:/root/.local/bin"
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
WORKDIR /root
COPY renovate.json /root/
# hadolint ignore=DL3008
RUN apt-get update && apt-get install --no-install-recommends -y -q \
    ca-certificates \
    curl \
    gcc \
    git \
    jq \
    libcairo2-dev \
    libev-dev \
    python3 \
    python3-dev \
    python3-pip \
    unzip \
    wget && \
    curl -sSL https://install.python-poetry.org | python3 - --version "$(jq -r .constraints.poetry /root/renovate.json)" && \
    poetry config virtualenvs.create false
WORKDIR /root
RUN wget -Ojquery.min.js https://code.jquery.com/jquery-3.7.1.min.js
RUN wget -Obootstrap.zip https://github.com/twbs/bootstrap/releases/download/v5.3.3/bootstrap-5.3.3-dist.zip && \
  unzip bootstrap.zip && \
  cp bootstrap*dist/css/bootstrap.min.css /root && \
  rm bootstrap.zip
WORKDIR /gamutrflib
COPY gamutrflib /gamutrflib/
RUN if [ "${POETRY_CACHE}" != "" ] ; then echo using cache "${POETRY_CACHE}" ; poetry source add --priority=default local "${POETRY_CACHE}" ; fi
RUN poetry install --no-interaction --no-ansi --no-dev
WORKDIR /gamutrfwaterfall
COPY gamutrfwaterfall /gamutrfwaterfall/
# TODO: handle caching for pycairo
RUN poetry run pip install --no-cache-dir pycairo=="$(grep pycairo pyproject.toml | grep -Eo '[0-9\.]+')"
RUN if [ "${POETRY_CACHE}" != "" ] ; then echo using cache "${POETRY_CACHE}" ; poetry source add --priority=default local "${POETRY_CACHE}" ; fi
RUN poetry install --no-interaction --no-ansi --without dev

FROM ubuntu:22.04
ENV DEBIAN_FRONTEND noninteractive
ENV PATH="${PATH}:/root/.local/bin"
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get update && apt-get install --no-install-recommends -y -q \
    curl \
    git \
    libev4 \
    libcairo2 \
    python3
COPY --from=installer /root/.local /root/.local
COPY --from=installer /usr/local /usr/local
COPY --from=installer /gamutrflib /gamutrflib
COPY --from=installer /gamutrfwaterfall /gamutrfwaterfall
COPY --from=installer /root/bootstrap.min.css /gamutrfwaterfall/gamutrfwaterfall/static
COPY --from=installer /root/jquery.min.js /gamutrfwaterfall/gamutrfwaterfall/static
CMD ["gamutrf-waterfall", "--help"]
