# TODO secure with certs: https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-the-mosquitto-mqtt-messaging-broker-on-ubuntu-18-04-quickstart
FROM alpine:3.18
LABEL maintainer="Charlie Lewis <clewis@iqt.org>"
RUN apk add --update curl mosquitto && rm -rf /var/cache/apk/*
COPY mosquitto.conf /etc/mosquitto/mosquitto.conf
EXPOSE 1883
ENTRYPOINT ["/usr/sbin/mosquitto", "-v", "-c", "/etc/mosquitto/mosquitto.conf"]
