FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /root
RUN apt-get update && \
    apt-get install -y \
      git \
      python3-pip
RUN pip config set global.no-cache-dir false && \
  git clone https://github.com/pytorch/serve -b v0.9.0 && \
  cd serve && \
  python3 ./ts_scripts/install_dependencies.py --cuda cu118 --environment prod && \
  pip3 install . && \
  pip3 install -r examples/object_detector/yolo/yolov8/requirements.txt && \
  cd .. && \
  rm -rf serve
RUN /usr/local/bin/torchserve --help

# see Dockerfile.torchserve for example, but use
# docker run --gpus all -ti iqtlabs/gamutrf-cuda-torchserve:latest bash
# ensure nvidia-container-toolkit is installed (https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html)
# CUDA version on the host must be same or later, than that in this container.
