FROM ubuntu:24.04 AS vkfft-builder
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  ca-certificates \
  cmake \
  git \
  libvulkan-dev \
  python3-dev
WORKDIR /root
RUN git clone https://github.com/DTolm/VkFFT -b v1.3.4
WORKDIR /root/VkFFT/build
RUN CMAKE_BUILD_TYPE=Release cmake -DGLSLANG_GIT_TAG=13.0.0 .. && make -j "$(nproc)"

FROM ubuntu:24.04
# TODO: ideally, should be packaged such that cmake can find it.
# hadolint ignore=DL3008
WORKDIR /root
COPY bin/install-nv.sh /root
RUN if [ "$(arch)" = "x86_64" ] ; then /root/install-nv.sh ; fi && \
    apt-get update && apt-get install -y --no-install-recommends libvulkan1
COPY --from=vkfft-builder /root/VkFFT /root/VkFFT
CMD ["/root/VkFFT/build/VkFFT_TestSuite", "-devices"]

# Test that GPU can be accessed by VkFFT:
# $ docker run --gpus all --device /dev/dri/renderD128:/dev/dri/renderD128 -ti iqtlabs/gamutrf-vkfft
# Device id: 0 name: NVIDIA GeForce RTX 4070 Ti API:1.3.260
