FROM ubuntu:22.04 as torchsig-builder
WORKDIR /root
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends build-essential ca-certificates cmake git python3-pip python3-dev && pip install -U pip
# Cause torch CPU only to be installed, no cuda dependencies
RUN pip install torch --extra-index-url https://download.pytorch.org/whl/cpu
RUN git clone https://github.com/TorchDSP/torchsig -b v0.4.1
WORKDIR /root/torchsig
RUN sed -i -E "s/torch==[0-9\.]+/torch/g" pyproject.toml
RUN pip install .

FROM iqtlabs/gamutrf:latest
WORKDIR /root
ENV DEBIAN_FRONTEND noninteractive
# TODO: find a better way cherrypick just Torchsig itself, without Torch et al. Torchsig transforms have dependencies on
# Torch, even though we don't need Torch for the standalone transforms we want.
COPY --from=torchsig-builder /usr/local/lib/python3.10/dist-packages/torchsig /usr/local/lib/python3.10/dist-packages/torchsig
COPY --from=torchsig-builder /usr/local/lib/python3.10/dist-packages/torch /usr/local/lib/python3.10/dist-packages/torch
RUN apt-get update && apt-get install -y --no-install-recommends python3-pip && pip3 install PyWavelets numba && apt-get purge -y  python3-pip
RUN python3 -c "from torchsig.transforms import transforms"
RUN python3 -c "from gamutrf import grscan"
