FROM ubuntu:22.04 as uhd_sample_recorder-builder
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  ca-certificates \
  cmake \
  git \
  libboost-all-dev \
  libuhd-dev \
  libvulkan-dev \
  sudo
WORKDIR /root
RUN git clone https://github.com/iqtlabs/uhd_sample_recorder -b v1.0.11
WORKDIR /root/uhd_sample_recorder
RUN ./bin/install-deps.sh && rm -rf VkFFT
COPY --from=iqtlabs/gamutrf-vkfft:latest /root/VkFFT /root/uhd_sample_recorder/VkFFT
RUN sed -i '/VkFFT/d' ./bin/build.sh && ./bin/build.sh && cp build/uhd_sample_recorder /usr/local/bin

FROM ubuntu:22.04
COPY --from=uhd_sample_recorder-builder /usr/local /usr/local
