FROM ubuntu:24.04 AS uhd_sample_recorder-builder
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  ca-certificates \
  cmake \
  git \
  libboost-all-dev \
  libuhd-dev \
  libvulkan-dev \
  sudo
WORKDIR /root/.config/pip
COPY pip.conf pip.conf
WORKDIR /root
RUN git clone https://github.com/iqtlabs/uhd_sample_recorder -b v1.0.12
WORKDIR /root/uhd_sample_recorder
RUN sed -i "/git clone/d" bin/install-deps.sh && echo "true" >> bin/install-deps.sh && bin/install-deps.sh
COPY --from=iqtlabs/gamutrf-vkfft:latest /root/VkFFT /root/uhd_sample_recorder/VkFFT
COPY --from=iqtlabs/gamutrf-sigmf:latest /usr/local /usr/local
WORKDIR /root/uhd_sample_recorder/build
RUN cmake ../lib && make -j $(nproc) && cp uhd_sample_recorder /usr/local/bin

FROM ubuntu:24.04
COPY --from=uhd_sample_recorder-builder /usr/local /usr/local
