FROM ubuntu:22.04 as torchsig-builder
WORKDIR /root
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends build-essential ca-certificates cmake git python3-pip python3-dev && pip install -U pip
RUN pip install git+https://github.com/TorchDSP/torchsig@v0.4.1

FROM iqtlabs/gamutrf:latest
WORKDIR /root
ENV DEBIAN_FRONTEND noninteractive
# TODO: find a better way cherrypick just Torchsig itself, without Torch et al.
COPY --from=torchsig-builder /usr/local/lib/python3.10/dist-packages/torchsig /usr/local/lib/python3.10/dist-packages/torchsig
RUN apt-get update && apt-get install -y --no-install-recommends python3-pip && pip3 install PyWavelets numba torch --extra-index-url https://download.pytorch.org/whl/cpu && apt-get purge -y  python3-pip
RUN python3 -c "from torchsig.transforms import transforms"
RUN python3 -c "from gamutrf import grscan"
