version: '3'
networks:
  gamutrf:
services:
  mavlink-api:
    image: iqtlabs/gamutrf-mavlink-api:latest
    build:
      context: utils/mavlink-api
      dockerfile: utils/mavlink-api/Dockerfile
    ports:
      - "8888:8888"
    devices:
      - "/dev/pixhawk_serial:/dev/tty.serial1"
    networks:
      - gamutrf
    restart: unless-stopped
