version: '3'
networks:
  gamutrf:
services:
  mavlink-api:
    image: iqtlabs/gamutrf-mavlink-api:latest
    build:
      context: .
      dockerfile: Dockerfile.mavlink-api
    ports:
      - "8888:8888"
    devices:
      - "/dev/pixhawk_serial:/dev/tty.serial1"
    networks:
      - gamutrf
    restart: unless-stopped
  #mqtt-publisher:
  #  image: iqtlabs/gamutrf-mavlink-mqtt-publisher:latest
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.mqtt-publisher
  #  networks:
  #    - gamutrf
  #  environment:
  #    - MQTT_IP=mqtt
  #    - MQTT_PORT=1883
  #    - MQTT_TOPIC=gamutrf/targets
  #    - QUERY_INTERVAL=1
  #    - URL_LIST=[["drone", "http://mavlink-api0:8888/gps-data"], ["controller", "http://mavlink-api1:8888/gps-data"]] # Example: [["target1", "https://example1.com"], ["target2", "https://example2.com"]]
  #  restart: unless-stopped


