# nosemgrep:github.workflows.config.dockerfile-source-not-pinned
FROM python:3.11-slim

WORKDIR /app
ENV PYTHONPATH=${PYTHONPATH}:${PWD}
RUN apt-get update -yq && apt-get install -yq jq && apt-get clean

COPY renovate.json .
RUN pip3 install "$(jq -r .constraints.poetry renovate.json)"
COPY utils/mavlink-api/pyproject.toml .
RUN poetry config virtualenvs.create false
RUN poetry install --no-dev

COPY utils/mavlink-api/mqtt-publisher.py .

# nosemgrep:github.workflows.config.missing-user
CMD ["python3", "mqtt-publisher.py"]
