version: '3'
networks:
  gamutrf:
services:
  mavlink-api:
    image: iqtlabs/gamutrf-mavlink-api:latest
    build:
      context: .
      dockerfile: Dockerfile.mavlink-api
    ports:
      - "8888:8888"
    devices:
      - "/dev/pixhawk_serial:/dev/tty.serial1"
    networks:
      - gamutrf
    restart: unless-stopped
  #mavlink-api-drone:
  #  image: iqtlabs/gamutrf-mavlink-api:latest
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.mavlink-api
  #  ports:
  #    - "8889:8888"
  #  devices:
  #    - "/dev/ttyUSB0:/dev/tty.serial1"
  #  networks:
  #    - gamutrf
  #  restart: unless-stopped
  #mavlink-api-controller:
  #  image: iqtlabs/gamutrf-mavlink-api:latest
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.mavlink-api
  #  ports:
  #    - "8890:8888"
  #  devices:
  #    - "/dev/ttyUSB1:/dev/tty.serial1"
  #  networks:
  #    - gamutrf
  #  restart: unless-stopped
  #mqtt-publisher:
  #  image: iqtlabs/gamutrf-mavlink-mqtt-publisher:latest
  #  build:
  #    context: .
  #    dockerfile: Dockerfile.mqtt-publisher
  #  networks:
  #    - gamutrf
  #  environment:
  #    - MQTT_IP=mqtt
  #    - MQTT_PORT=1883
  #    - MQTT_TOPIC=gamutrf/targets
  #    - QUERY_INTERVAL=1
  #    - URL_LIST=[["controller", "http://mavlink-api-controller:8888/gps-data"], ["drone", "http://mavlink-api-drone:8888/gps-data"]] # Example: [["target1", "https://example1.com"], ["target2", "https://example2.com"]]
  #  restart: unless-stopped