[tool.poetry]
name = "gamutrfwaterfall"
version = "0.5.40"
description = "An orchestrated SDR scanner"
authors = ["cglewis <clewis@iqt.org>"]
license = "Apache-2.0"
packages = [
    { include = "gamutrfwaterfall" },
]

[tool.poetry.dependencies]
Flask = "3.0.2"
cairocffi = "1.6.1"
matplotlib = "3.8.3"
numpy = "1.26.4"
pandas = "2.2.1"
pycairo = "1.26.0"
python = ">=3.9,<3.13"
pyzmq = "25.1.2"
scipy = "1.12.0"
zstandard = "0.22.0"
requests = "2.31.0"

[tool.poetry.scripts]
gamutrf-waterfall = 'gamutrfwaterfall.waterfall:main'

[tool.poetry.urls]
homepage = "https://github.com/IQTLabs/gamutRF"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
