[tool.poetry]
name = "gamutrfwaterfall"
version = "0.5.40"
description = "An orchestrated SDR scanner"
authors = ["cglewis <clewis@iqt.org>"]
license = "Apache-2.0"
packages = [
    { include = "gamutrfwaterfall" },
]

[tool.poetry.dependencies]
Flask = "3.0.1"
cairocffi = "^1.3.0"
matplotlib = "3.8.2"
numpy = "1.26.3"
pandas = "2.1.4"
pycairo = "^1.21.0"
python = ">=3.9,<3.13"
pyzmq = "^25.1.0"
scipy = "1.12.0"
zstandard = "0.22.0"

[tool.poetry.scripts]
gamutrf-waterfall = 'gamutrfwaterfall.waterfall:main'

[tool.poetry.urls]
homepage = "https://github.com/IQTLabs/gamutRF"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
