name: CI Test

on: [push, pull_request]

jobs:

  ci-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:gnuradio/gnuradio-releases-3.9
          sudo apt-get update && sudo apt-get install -y --no-install-recommends gcc git g++ libev-dev python3-dev gnuradio-dev python3-pip gnuradio sox
          git clone https://github.com/ThomasHabets/gr-habets39 && cd gr-habets39 && mkdir build && cd build && cmake .. && sudo make install && cd ../..
          sudo ln -s /usr/local/lib/python3/dist-packages/* /usr/local/lib/python${{ matrix.python-version }}/dist-packages
          sudo ldconfig -v
          python3 -c "from gnuradio import *"
          python3 -c "import habets39"
          poetry install --no-interaction

      - name: Code Quality - Black
        run: |
          poetry run black gamutrf --check

      - name: Code Quality - Pytype
        run: |
          poetry run pytype gamutrf/

      - name: Code Quality - Pylint
        run: |
          poetry run pylint --fail-under=7 gamutrf/

      - name: Test with pytest
        run: |
          poetry run pytest --cov-report term-missing --cov=. --cov-report=xml
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: /home/runner/work/gamutrf/gamutrf/coverage.xml
          fail_ci_if_error: true
