name: CI Test

on: [push, pull_request]

jobs:
  ci-test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
          version: 1.8.3
      - name: Get dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends \
            yamllint
      - name: Code Quality - yamllint
        run: |
          yamllint -s *yml
      - name: Install poetry dependencies
        run: |
          poetry config virtualenvs.create false && \
          poetry run pip install black
      - name: Code Quality - Black
        run: |
          poetry run black gamutrf --check
          poetry run black gamutrflib --check
          poetry run black gamutrfwaterfall --check
          poetry run black utils --check
